# Generated by Django 3.1.7 on 2021-03-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='values',
            new_name='Value',
        ),
    ]
